export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  image: string;
  publishDate: string;
  author: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'best-wireless-headphones',
    title: '10 Best Wireless Headphones for 2024',
    description: 'Discover the top wireless headphones that deliver exceptional sound quality and comfort.',
    category: 'Electronics',
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg',
    publishDate: '2024-12-15',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-coffee-makers',
    title: '10 Best Coffee Makers for Home Brewing',
    description: 'From espresso machines to drip coffee makers, find your perfect morning companion.',
    category: 'Kitchen',
    image: 'https://images.pexels.com/photos/324028/pexels-photo-324028.jpeg',
    publishDate: '2024-12-10',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-running-shoes',
    title: '10 Best Running Shoes for Athletes',
    description: 'Performance-tested running shoes that provide comfort and support for every stride.',
    category: 'Sports',
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg',
    publishDate: '2024-12-08',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-skincare-products',
    title: '10 Best Skincare Products for Glowing Skin',
    description: 'Premium skincare essentials that deliver visible results for all skin types.',
    category: 'Beauty',
    image: 'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg',
    publishDate: '2024-12-05',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-smart-watches',
    title: '10 Best Smart Watches for Fitness Tracking',
    description: 'Track your health and stay connected with these advanced smartwatches.',
    category: 'Electronics',
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg',
    publishDate: '2024-12-01',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-backpacks',
    title: '10 Best Backpacks for Travel and Work',
    description: 'Durable and stylish backpacks designed for modern professionals and travelers.',
    category: 'Travel',
    image: 'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg',
    publishDate: '2024-11-28',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-yoga-mats',
    title: '10 Best Yoga Mats for Every Practice Level',
    description: 'Find the perfect yoga mat with excellent grip, cushioning, and durability.',
    category: 'Fitness',
    image: 'https://images.pexels.com/photos/3822621/pexels-photo-3822621.jpeg',
    publishDate: '2024-11-25',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-laptop-bags',
    title: '10 Best Laptop Bags for Professionals',
    description: 'Protective and stylish laptop bags that combine functionality with fashion.',
    category: 'Tech Accessories',
    image: 'https://images.pexels.com/photos/2081199/pexels-photo-2081199.jpeg',
    publishDate: '2024-11-20',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-kitchen-knives',
    title: '10 Best Kitchen Knives for Home Chefs',
    description: 'Sharp, durable, and well-balanced knives that make cooking a pleasure.',
    category: 'Kitchen',
    image: 'https://images.pexels.com/photos/2291599/pexels-photo-2291599.jpeg',
    publishDate: '2024-11-15',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-gaming-chairs',
    title: '10 Best Gaming Chairs for Comfort and Performance',
    description: 'Ergonomic gaming chairs that support long gaming sessions with style.',
    category: 'Gaming',
    image: 'https://images.pexels.com/photos/2047905/pexels-photo-2047905.jpeg',
    publishDate: '2024-11-10',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-water-bottles',
    title: '10 Best Water Bottles for Hydration on the Go',
    description: 'Insulated and eco-friendly water bottles that keep drinks at perfect temperature.',
    category: 'Lifestyle',
    image: 'https://images.pexels.com/photos/1000084/pexels-photo-1000084.jpeg',
    publishDate: '2024-11-05',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-desk-lamps',
    title: '10 Best Desk Lamps for Your Workspace',
    description: 'Adjustable and energy-efficient desk lamps that reduce eye strain.',
    category: 'Home Office',
    image: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg',
    publishDate: '2024-11-01',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-bluetooth-speakers',
    title: '10 Best Bluetooth Speakers for Music Lovers',
    description: 'Portable speakers with impressive sound quality and long battery life.',
    category: 'Electronics',
    image: 'https://images.pexels.com/photos/1279628/pexels-photo-1279628.jpeg',
    publishDate: '2024-10-28',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-air-purifiers',
    title: '10 Best Air Purifiers for Clean Indoor Air',
    description: 'HEPA air purifiers that remove allergens and improve air quality.',
    category: 'Home & Living',
    image: 'https://images.pexels.com/photos/4098778/pexels-photo-4098778.jpeg',
    publishDate: '2024-10-25',
    author: 'FashionLinker Team',
  },
  {
    slug: 'best-camera-bags',
    title: '10 Best Camera Bags for Photographers',
    description: 'Protective camera bags with smart organization for all your photography gear.',
    category: 'Photography',
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg',
    publishDate: '2024-10-20',
    author: 'FashionLinker Team',
  },
  {
    slug: 'crunchyroll-ultimate-anime-streaming',
    title: 'Crunchyroll: Your Ultimate Destination for Anime Streaming',
    description: 'Discover the world\'s largest anime streaming platform with thousands of episodes, simulcasts, and exclusive content.',
    category: 'Entertainment',
    image: 'https://images.pexels.com/photos/2422280/pexels-photo-2422280.jpeg',
    publishDate: '2026-03-02',
    author: 'FashionLinker Team',
  },
  {
    slug: 'vilebrequin-luxury-swimwear-summer-guide',
    title: 'Vilebrequin: The Art of Luxury Swimwear Since Saint-Tropez 1971',
    description: 'Discover Vilebrequin\'s iconic luxury swim trunks, resort wear, and summer collections. From hand-embroidered designs to water-reactive prints, explore why this French house defines poolside elegance.',
    category: 'Fashion',
    image: 'https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg',
    publishDate: '2026-04-20',
    author: 'FashionLinker Team',
  },
  {
    slug: 'enterprise-car-club-sustainable-smart-travel-guide',
    title: 'The Smart Traveler’s Guide: Why Enterprise Car Club is Revolutionizing Modern Mobility',
    description: 'Say goodbye to maintenance costs and insurance hassle. Discover how Enterprise Car Club offers 24/7 on-demand car rentals right around your corner.',
    category: 'Travel',
    image: 'https://images.pexels.com/photos/4606346/pexels-photo-4606346.jpeg', // 精选的高清商用汽车出行配图
    publishDate: '2026-05-01',
    author: 'FashionLinker Team',
  },
];
